/*
权限常量定义
定义所有系统权限和角色默认权限
*/

import type { UserRole } from '@/api/types'

/** 权限标识常量 */
export const PERMISSIONS = {
  // 页面级权限
  DASHBOARD_VIEW: 'dashboard:view',
  PROFILE_VIEW: 'profile:view',
  OBJECT_VIEW: 'object:view',
  USER_VIEW: 'user:view',
  AUDIT_VIEW: 'audit:view',
  QUICK_START_VIEW: 'quickStart:view',
  API_DOCS_VIEW: 'apiDocs:view',
  SETTINGS_VIEW: 'settings:view',
  HELP_VIEW: 'help:view',
  TEST_VIEW: 'test:view',

  // 操作级权限
  OBJECT_CREATE: 'object:create',
  OBJECT_DELETE: 'object:delete',
  OBJECT_EDIT: 'object:edit',
  USER_MANAGE: 'user:manage',
  AUDIT_APPROVE: 'audit:approve',
  AUDIT_REJECT: 'audit:reject',
  AUDIT_REVOKE: 'audit:revoke',
  DATA_EXPORT: 'data:export',
  DATA_IMPORT: 'data:import',
  AUDIT_BATCH: 'audit:batch',
  SYSTEM_CONFIG: 'system:config'
} as const

/** 权限值类型 */
export type PermissionValue = (typeof PERMISSIONS)[keyof typeof PERMISSIONS]

/** 角色默认权限映射 */
export const ROLE_PERMISSIONS: Record<UserRole, PermissionValue[]> = {
  SUPER_ADMIN: Object.values(PERMISSIONS),
  ADMIN: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.OBJECT_VIEW,
    PERMISSIONS.OBJECT_CREATE,
    PERMISSIONS.OBJECT_EDIT,
    PERMISSIONS.OBJECT_DELETE,
    PERMISSIONS.USER_VIEW,
    PERMISSIONS.USER_MANAGE,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_APPROVE,
    PERMISSIONS.AUDIT_REJECT,
    PERMISSIONS.AUDIT_REVOKE,
    PERMISSIONS.QUICK_START_VIEW,
    PERMISSIONS.API_DOCS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.HELP_VIEW,
    PERMISSIONS.DATA_EXPORT,
    PERMISSIONS.TEST_VIEW
  ],
  AUDITOR: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.OBJECT_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.AUDIT_APPROVE,
    PERMISSIONS.AUDIT_REJECT,
    PERMISSIONS.AUDIT_REVOKE,
    PERMISSIONS.QUICK_START_VIEW,
    PERMISSIONS.API_DOCS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.HELP_VIEW
  ],
  USER: [
    PERMISSIONS.DASHBOARD_VIEW,
    PERMISSIONS.PROFILE_VIEW,
    PERMISSIONS.AUDIT_VIEW,
    PERMISSIONS.QUICK_START_VIEW,
    PERMISSIONS.API_DOCS_VIEW,
    PERMISSIONS.SETTINGS_VIEW,
    PERMISSIONS.HELP_VIEW
  ],
  GUEST: [PERMISSIONS.DASHBOARD_VIEW, PERMISSIONS.PROFILE_VIEW, PERMISSIONS.OBJECT_VIEW]
}
